file_format: "1"
id: dactyl_manuform_5x6
name: Dactyl_manuform_5x6
type: shield
url: https://github.com/dongocduy/dactyl_5x6_zmk.git
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - dactyl_manuform_5x6_left
  - dactyl_manuform_5x6_right